import type { DatabaseSchema } from "../ast/types.ts";

export function generateMeta(schema: DatabaseSchema): string {
  const lines: string[] = [];

  lines.push(`// Generated by Aether Oracle — do not edit manually`);
  lines.push(`import type { AetherMeta } from "@yrrrrrf/aether";`);
  lines.push(``);

  // Read-only views set
  const views = schema.tables.filter((t) => t.isView);
  const viewKeys = views.map((v) => `"${v.schema}.${v.name}"`).join(", ");
  lines.push(`const READ_ONLY_VIEWS = new Set([${viewKeys}] as const);`);
  lines.push(``);

  // Primary key map
  lines.push(`const PRIMARY_KEYS = {`);
  for (
    const t of schema.tables.filter((t) =>
      !t.isView && t.primaryKeys.length > 0
    )
  ) {
    const key = `"${t.schema}.${t.name}"`;
    const pks = t.primaryKeys.map((k) => `"${k}"`).join(", ");
    lines.push(`  ${key}: [${pks}] as const,`);
  }
  lines.push(`} as const;`);
  lines.push(``);

  // Function signatures for runtime RPC validation
  // Note: we will populate this fully in Phase 4 once the AST supports functions,
  // but we set up the structure now so it compiles.
  lines.push(`const RPC_FUNCTIONS = {`);
  if (schema.functions) {
    for (const fn of schema.functions) {
      const requiredParams = fn.params
        .filter((p) => p.mode === "IN" && !p.hasDefault)
        .map((p) => `"${p.name}"`);
      lines.push(
        `  "${fn.schema}.${fn.name}": { required: [${
          requiredParams.join(", ")
        }] },`,
      );
    }
  }
  lines.push(`} as const;`);
  lines.push(``);

  lines.push(`export const aetherMeta = {`);
  lines.push(`  readOnlyViews: READ_ONLY_VIEWS,`);
  lines.push(`  primaryKeys: PRIMARY_KEYS,`);
  lines.push(`  rpcFunctions: RPC_FUNCTIONS,`);
  lines.push(`} satisfies AetherMeta;`);

  return lines.join("\n");
}
