import type { DatabaseSchema, Table } from "../ast/types.ts";
import { mapPostgresTypeToTs } from "../ast/mapper.ts";
import { toInterfaceName, toPascalCase } from "../utils.ts";

/**
 * Generates TypeScript interfaces and a unified DB map from a parsed DatabaseSchema.
 *
 * @param schema - The introspected database schema.
 * @param importFrom - The module path to import Aether runtime types from.
 * @param includeComments - Whether to include database comments in the generated output.
 * @returns The generated TypeScript source code.
 */
export function generateTypeScript(
  schema: DatabaseSchema,
  importFrom = "@yrrrrrf/aether",
  includeComments = true,
  zodImport?: string,
): string {
  const lines: string[] = [];

  // Header
  lines.push(`// deno-lint-ignore-file no-empty-interface`);
  lines.push(`// Generated by Aether Oracle`);
  lines.push(`// Do not edit manually`);
  lines.push(
    `import type { TableOperations, ViewOperations } from "${importFrom}";`,
  );
  lines.push(``);
  lines.push(
    `export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];`,
  );
  lines.push(``);

  if (zodImport) {
    lines.push(`import { z } from "npm:zod";`);
    lines.push(`import * as Z from "${zodImport}";`);
    lines.push(``);
  }

  // Enums
  for (const enm of schema.enums) {
    const enumName = toPascalCase(enm.name);
    const validValues = enm.values.map((v) => `"${v}"`).join(" | ");
    lines.push(`export type ${enumName} = ${validValues};`);
    lines.push(``);
  }

  // Tables
  for (const table of schema.tables) {
    lines.push(...generateTable(table, schema, includeComments, zodImport));
    lines.push(...generateRelations(table, schema));
    lines.push(``);
  }

  // Main DB Interface
  lines.push(`export interface DB {`);
  // Group by schema
  const schemas = new Set(schema.tables.map((t) => t.schema));
  for (const s of schemas) {
    lines.push(`  ${s}: {`);
    const schemaTables = schema.tables.filter((t) => t.schema === s);
    for (const t of schemaTables) {
      const interfaceName = toInterfaceName(t.schema, t.name);
      const relationsName = `${interfaceName}Relations`;
      if (t.isView) {
        lines.push(
          `    ${t.name}: ViewOperations<${interfaceName}, ${relationsName}>;`,
        );
      } else {
        const pkUnion = t.primaryKeys.length > 0
          ? t.primaryKeys.map((k) => `"${k}"`).join(" | ")
          : "never";
        lines.push(
          `    ${t.name}: TableOperations<${interfaceName}, ${relationsName}, ${pkUnion}>;`,
        );
      }
    }
    lines.push(`  };`);
  }

  if (schema.functions && schema.functions.length > 0) {
    lines.push(`  rpc: RpcFunctions;`);
  }

  lines.push(`}`);

  if (schema.functions && schema.functions.length > 0) {
    const enumUdtNames = new Set(schema.enums.map((e) => e.name));
    const fnRows = schema.functions.map((fn) => {
      const args = fn.params
        .filter((p) =>
          p.mode === "IN" || p.mode === "INOUT" || p.mode === "VARIADIC"
        )
        .map((p) => {
          let t = mapPostgresTypeToTs(p.type, p.type, enumUdtNames);
          const foundEnum = schema.enums.find((e) => e.name === p.type);
          if (foundEnum) t = toPascalCase(foundEnum.name);
          return `${p.name || "arg"}${p.hasDefault ? "?" : ""}: ${t}`;
        })
        .join(", ");

      let returnTs = mapPostgresTypeToTs(
        fn.returnType,
        fn.returnType,
        enumUdtNames,
      );
      const foundRetEnum = schema.enums.find((e) => e.name === fn.returnType);
      if (foundRetEnum) returnTs = toPascalCase(foundRetEnum.name);
      if (fn.returnType === "json" || fn.returnType === "jsonb") {
        returnTs = "Json";
      }

      const ret = fn.isSetReturning ? `${returnTs}[]` : returnTs;
      let comment = "";
      if (includeComments && fn.description) {
        comment = `\n  /** ${fn.description} */\n`;
      }
      return `${comment}  "${fn.schema}.${fn.name}": (${args}) => Promise<${ret}>;`;
    });

    lines.push(``);
    lines.push(`export interface RpcFunctions {`);
    lines.push(...fnRows);
    lines.push(`}`);
  }

  return lines.join("\n");
}

function generateRelations(table: Table, _schema: DatabaseSchema): string[] {
  const lines: string[] = [];
  const interfaceName = `${toInterfaceName(table.schema, table.name)}Relations`;

  lines.push(`export interface ${interfaceName} {`);
  const emittedRels = new Set<string>();

  for (const fk of table.foreignKeys) {
    const relKey = fk.targetSchema + "." + fk.targetTable;
    if (emittedRels.has(relKey)) continue;
    emittedRels.add(relKey);

    const targetName = toInterfaceName(fk.targetSchema, fk.targetTable);
    // PostgREST convention: use the table name for the relationship
    lines.push(`  ${fk.targetTable}?: ${targetName};`);
  }
  lines.push(`}`);

  return lines;
}

function generateTable(
  table: Table,
  schema: DatabaseSchema,
  includeComments: boolean,
  zodImport?: string,
): string[] {
  const lines: string[] = [];
  const interfaceName = toInterfaceName(table.schema, table.name);
  const enumUdtNames = new Set(schema.enums.map((e) => e.name));

  if (zodImport) {
    if (includeComments) {
      lines.push(`/** Inferred from Zod Schema */`);
      // Foreign Key Comments (The Graph)
      if (table.foreignKeys.length > 0) {
        lines.push(`// Relations:`);
        for (const fk of table.foreignKeys) {
          lines.push(
            `// -> ${fk.column} joins to ${fk.targetSchema}.${fk.targetTable}.${fk.targetColumn}`,
          );
        }
      }
    }
    lines.push(
      `export type ${interfaceName} = z.infer<typeof Z.${interfaceName}Schema>;`,
    );
  } else {
    lines.push(`export interface ${interfaceName} {`);

    // Foreign Key Comments (The Graph)
    // We check table.foreignKeys
    if (table.foreignKeys.length > 0) {
      lines.push(`  // Relations:`);
      for (const fk of table.foreignKeys) {
        lines.push(
          `  // -> ${fk.column} joins to ${fk.targetSchema}.${fk.targetTable}.${fk.targetColumn}`,
        );
      }
    }

    for (const col of table.columns) {
      // Resolve type
      let tsType = mapPostgresTypeToTs(col.dataType, col.udtName, enumUdtNames);

      // Check if it is an enum
      const foundEnum = schema.enums.find((e) =>
        e.name === col.udtName && e.schema === table.schema
      );
      if (foundEnum) {
        tsType = toPascalCase(foundEnum.name);
      }

      if (col.dataType === "json" || col.dataType === "jsonb") {
        tsType = "Json";
      }

      if (includeComments && col.comment) {
        lines.push(`  /** ${col.comment} */`);
      }

      const optionalMark = col.isNullable ? "?" : "";
      const nullType = col.isNullable ? " | null" : "";

      lines.push(`  ${col.name}${optionalMark}: ${tsType}${nullType};`);
    }

    lines.push(`}`);
  }

  if (table.primaryKeys.length > 0) {
    const pkFields = table.primaryKeys.map((k) => `"${k}"`).join(" | ");
    lines.push(``);
    lines.push(
      `export type ${interfaceName}PKFilter = Required<Pick<${interfaceName}, ${pkFields}>>;`,
    );
  }

  return lines;
}
