import type { Column, DatabaseSchema, Table } from "../ast/types.ts";
import { toInterfaceName, toPascalCase, toSchemaName } from "../utils.ts";

/**
 * Generates pure Zod validation schemas for all tables and enums in the database.
 * Maps dynamic constraints like `.max()` or numeric `.multipleOf()` based on SQL metadata
 * and generates a dictionary map to retrieve them at runtime.
 *
 * @param schema - The parsed database schema extracted by the introspector.
 * @param importFrom - The module path mapping runtime types.
 * @returns The emitted Zod validation dictionary code.
 */
export function generateZod(
  schema: DatabaseSchema,
  importFrom = "@yrrrrrf/aether",
): string {
  const lines: string[] = [];

  lines.push(`// Generated by Aether Oracle (Zod)`);
  lines.push(`import { z } from "zod";`);
  lines.push(`import type { ValidationStrategy } from "${importFrom}";`);
  lines.push(``);
  lines.push(`// Shared recursive JSON type`);
  lines.push(
    `type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };`,
  );
  lines.push(`const JsonSchema: z.ZodType<JsonValue> = z.lazy(() =>`);
  lines.push(`  z.union([`);
  lines.push(`    z.string(), z.number(), z.boolean(), z.null(),`);
  lines.push(`    z.array(JsonSchema),`);
  lines.push(`    z.record(JsonSchema),`);
  lines.push(`  ])`);
  lines.push(`);`);
  lines.push(``);

  // Enums
  for (const enm of schema.enums) {
    const enumName = toPascalCase(enm.name) + "Schema";
    // Zod enum requires non-empty array of strings
    if (enm.values.length > 0) {
      // [val1, val2, ...]
      const values = enm.values.map((v) => `"${v}"`).join(", ");
      lines.push(`export const ${enumName} = z.enum([${values}]);`);
    } else {
      lines.push(
        `export const ${enumName} = z.string(); // Empty enum fallback`,
      );
    }
    lines.push(``);
  }

  // Tables
  for (const table of schema.tables) {
    lines.push(...generateTableZod(table, schema));
    lines.push(``);
  }

  // Validators Map
  lines.push(`export const validators: Record<string, ValidationStrategy> = {`);
  for (const table of schema.tables) {
    const schemaName = toSchemaName(table.schema, table.name);
    lines.push(
      `  "${table.schema}.${table.name}": ${schemaName} as ValidationStrategy,`,
    );
  }
  lines.push(`};`);
  lines.push(``);
  lines.push(
    `export function getValidator(schema: string, table: string): ValidationStrategy | undefined {`,
  );
  lines.push(`  return validators[schema + "." + table];`);
  lines.push(`}`);

  return lines.join("\n");
}

function generateTableZod(table: Table, schema: DatabaseSchema): string[] {
  const lines: string[] = [];
  const schemaName = toSchemaName(table.schema, table.name);
  const insertSchemaName = toInterfaceName(table.schema, table.name) +
    "InsertSchema";

  // 1. Select Schema
  lines.push(`export const ${schemaName} = z.object({`);
  for (const col of table.columns) {
    let zodType = getBaseZodType(col, schema, table);
    if (col.isNullable) zodType += ".nullable()";
    lines.push(`  ${col.name}: ${zodType},`);
  }
  lines.push(`});`);
  lines.push(``);

  // 2. Insert Schema
  lines.push(`export const ${insertSchemaName} = z.object({`);
  for (const col of table.columns) {
    let zodType = getBaseZodType(col, schema, table);
    if (col.isNullable) zodType += ".nullable()";

    if (col.hasDefault || col.isNullable) {
      zodType += ".optional()";
    }

    lines.push(`  ${col.name}: ${zodType},`);
  }
  lines.push(`});`);

  return lines;
}

function getBaseZodType(
  col: Column,
  schema: DatabaseSchema,
  table: Table,
): string {
  let zodType = "z.unknown()";

  // Check Enum
  const foundEnum = schema.enums.find((e) =>
    e.name === col.udtName && e.schema === table.schema
  );
  if (foundEnum) {
    return toPascalCase(foundEnum.name) + "Schema";
  }

  // Map basic types
  switch (col.dataType) {
    case "boolean":
      zodType = "z.boolean()";
      break;
    case "integer":
    case "smallint":
    case "real":
    case "double precision":
    case "numeric":
      if (
        col.numericPrecision !== undefined && col.numericScale !== undefined
      ) {
        const step = Math.pow(10, -col.numericScale);
        zodType = `z.number().multipleOf(${step})`;
      } else {
        zodType = "z.number()";
      }
      break;
    case "character varying":
    case "character":
      if (col.maxLength) {
        zodType = col.dataType === "character"
          ? `z.string().length(${col.maxLength})`
          : `z.string().max(${col.maxLength})`;
      } else {
        zodType = "z.string()";
      }
      break;
    case "bigint":
    case "text":
    case "uuid":
    case "inet":
    case "cidr":
    case "macaddr":
    case "timestamp with time zone":
    case "timestamp without time zone":
    case "date":
    case "time without time zone":
    case "interval":
      zodType = "z.string()";
      break;
    case "json":
    case "jsonb":
      zodType = "JsonSchema";
      break;
    case "ARRAY": {
      const inner = col.udtName.startsWith("_")
        ? col.udtName.slice(1)
        : col.udtName;
      const innerCol = { ...col, dataType: inner, udtName: inner };
      zodType = `z.array(${getBaseZodType(innerCol, schema, table)})`;
      break;
    }
  }
  return zodType;
}
