import type { Column, DatabaseSchema, Table } from "../ast/types.ts";
import { toInterfaceName, toPascalCase, toSchemaName } from "../utils.ts";

export function generateZod(
  schema: DatabaseSchema,
  importFrom = "@yrrrrrf/aether",
): string {
  const lines: string[] = [];

  lines.push(`// Generated by Aether Oracle (Zod)`);
  lines.push(`import { z } from "zod";`);
  lines.push(`import type { ValidationStrategy } from "${importFrom}";`);
  lines.push(``);

  // Enums
  for (const enm of schema.enums) {
    const enumName = toPascalCase(enm.name) + "Schema";
    // Zod enum requires non-empty array of strings
    if (enm.values.length > 0) {
      // [val1, val2, ...]
      const values = enm.values.map((v) => `"${v}"`).join(", ");
      lines.push(`export const ${enumName} = z.enum([${values}]);`);
    } else {
      lines.push(
        `export const ${enumName} = z.string(); // Empty enum fallback`,
      );
    }
    lines.push(``);
  }

  // Tables
  for (const table of schema.tables) {
    lines.push(...generateTableZod(table, schema));
    lines.push(``);
  }

  // Validators Map
  lines.push(`export const validators: Record<string, ValidationStrategy> = {`);
  for (const table of schema.tables) {
    const schemaName = toSchemaName(table.schema, table.name);
    lines.push(
      `  "${table.schema}.${table.name}": ${schemaName} as ValidationStrategy,`,
    );
  }
  lines.push(`};`);
  lines.push(``);
  lines.push(
    `export function getValidator(schema: string, table: string): ValidationStrategy | undefined {`,
  );
  lines.push(`  return validators[schema + "." + table];`);
  lines.push(`}`);

  return lines.join("\n");
}

function generateTableZod(table: Table, schema: DatabaseSchema): string[] {
  const lines: string[] = [];
  const schemaName = toSchemaName(table.schema, table.name);
  const insertSchemaName = toInterfaceName(table.schema, table.name) +
    "InsertSchema";

  // 1. Select Schema
  lines.push(`export const ${schemaName} = z.object({`);
  for (const col of table.columns) {
    let zodType = getBaseZodType(col, schema, table);
    if (col.isNullable) zodType += ".nullable()";
    lines.push(`  ${col.name}: ${zodType},`);
  }
  lines.push(`});`);
  lines.push(``);

  // 2. Insert Schema
  lines.push(`export const ${insertSchemaName} = z.object({`);
  for (const col of table.columns) {
    let zodType = getBaseZodType(col, schema, table);
    if (col.isNullable) zodType += ".nullable()";

    if (col.hasDefault || col.isNullable) {
      zodType += ".optional()";
    }

    lines.push(`  ${col.name}: ${zodType},`);
  }
  lines.push(`});`);

  return lines;
}

function getBaseZodType(
  col: Column,
  schema: DatabaseSchema,
  table: Table,
): string {
  let zodType = "z.unknown()";

  // Check Enum
  const foundEnum = schema.enums.find((e) =>
    e.name === col.udtName && e.schema === table.schema
  );
  if (foundEnum) {
    return toPascalCase(foundEnum.name) + "Schema";
  }

  // Map basic types
  switch (col.dataType) {
    case "boolean":
      zodType = "z.boolean()";
      break;
    case "integer":
    case "smallint":
    case "real":
    case "double precision":
    case "numeric":
      zodType = "z.number()";
      break;
    case "bigint":
    case "text":
    case "character varying":
    case "character":
    case "uuid":
    case "inet":
    case "cidr":
    case "macaddr":
    case "timestamp with time zone":
    case "timestamp without time zone":
    case "date":
    case "time without time zone":
      zodType = "z.string()";
      break;
    case "json":
    case "jsonb":
      zodType = "z.any()";
      break;
    case "ARRAY":
      zodType = "z.array(z.unknown())";
      break;
  }
  return zodType;
}
